### ISSUE TITLE
support for docker events stream 

### ISSUE THREAD

**Issue by bhurlow** [lispyclouds/clj-docker-client#1]
looks like the spotify lib supports docker events: https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#monitor-dockers-events 

Open to a PR to add these events?

**Comment by lispyclouds** [comment]
I definitely planned for this. Will start on it. Any help is much appreciated!

**Comment by lispyclouds** [comment]
This is now possible with 0.4.0. Can be done similarly to https://github.com/lispyclouds/clj-docker-client#streaming-logs
