### ISSUE TITLE
Suggestion: Positional Arguments vs Maps

### ISSUE THREAD

**Issue by jvtrigueros** [lispyclouds/clj-docker-client#13]
The current API relies on positional arguments, so if I want to start a container but want to omit a few parts I'm doing something like:
```clojure
(docker/run conn "busybox" nil {} {} true)
```

I'm now looking for a way to set the container name when creating, but if I submit a PR, a new positional argument would need to be added. I know this change is a breaking change, but would allow you to add more options without affecting the position, so something like:

```clojure
(docker/run conn
  {:image "busybox"
   :cmd "sleep 10"
   :port-bindings {80 8080}
   :env-variables {"CHEESE" "cake"}
   :name "my-container" ;; feature request ;)
   :links {"db" "db"}   ;; feature request ;)
   :detached? true})
```

What do you think?

**Comment by lispyclouds** [comment]
This has been on my mind for a while, was planning to do it by removing the java layer completely and talk to the daemon's API directly for a much nicer data-driven access. This would mean a lot of work. The current API can be retrofitted to work with maps, and I'm okay with the chage too, but its difficult to get time now 😞 . A PR would be most welcome as I add features to this on a need to basis from the projects I use this in.

**Comment by jvtrigueros** [comment]
Completely understand!

I'll take a shot at this and will retain the positional arguments to prevent backward-incompatible changes.

**Comment by lispyclouds** [comment]
Thank you!

**Comment by lispyclouds** [comment]
Closed by https://github.com/lispyclouds/clj-docker-client/pull/14
