### ISSUE TITLE
Timeouts when waiting for containers to exit

### ISSUE THREAD

**Issue by olymk2** [lispyclouds/clj-docker-client#19]
Calling the code below causes a timeout, I think this is due to a built in timeout in the underlying library as i could not find a timeout set with in the code any where.

```
(c/invoke
            containers
            {:op     :ContainerCreate
             :params {:name "piper"
                      :body {:Image "bitnami/minideb:latest"
                             :Cmd ["bash" "-c" "echo 'waiting'; sleep 900"]}}})
```

The above results in this error, I have seen this running different commands which take a long time to exit, not sure how simple it is to handle this thought i would mention here for some thoughts on the issue, obviously being a wait it could be a long time before things finish.

```
** ERROR: **
JVM Exception: #error {
 :cause timeout
 :via
 [{:type java.net.SocketTimeoutException
   :message timeout
   :at [okio.SocketAsyncTimeout newTimeoutException Okio.kt 142]}]
 :trace
 [[okio.SocketAsyncTimeout newTimeoutException Okio.kt 142]
  [okio.AsyncTimeout exit$okio AsyncTimeout.kt 148]
  [okio.AsyncTimeout$source$1 read AsyncTimeout.kt 351]
  [okio.RealBufferedSource request RealBufferedSource.kt 207]
  [okio.RealBufferedSource require RealBufferedSource.kt 201]
  [okio.RealBufferedSource readHexadecimalUnsignedLong RealBufferedSource.kt 400]
  [okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource readChunkSize Http1ExchangeCodec.kt 450]
  [okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource read Http1ExchangeCodec.kt 429]
  [okhttp3.internal.connection.Exchange$ResponseBodySource read Exchange.kt 279]
  [okio.RealBufferedSource select RealBufferedSource.kt 231]
  [okhttp3.internal.Util readBomAsCharset Util.kt 255]
  [okhttp3.ResponseBody string ResponseBody.kt 187]
  [clj_docker_client.requests$fetch invokeStatic requests.clj 130]
  [clj_docker_client.requests$fetch invoke requests.clj 116]
  [clj_docker_client.core$invoke invokeStatic core.clj 115]
  [clj_docker_client.core$invoke invoke core.clj 94]
```

**Comment by lispyclouds** [comment]
Hey thanks for reporting, this looks like a genuine issue as I use [OkHttp](https://square.github.io/okhttp/) underneath and it defaults to **10s** on a lot of the timeout [settings](https://www.baeldung.com/okhttp-timeouts).

This is currently not configurable but this can be easily added.

Some options:
- Change all of them to no timeout and leave it unconfigurable. This is closest to the docker cli behavior. Easiest to implement.
- Allow a way to specify timeouts. More flexible
- No timeouts be default, but allows configuration
- Any more suggestions?

What's your opinion?

**Comment by lispyclouds** [comment]
The connect fn can be done something like this if going the specifying timeouts way:
```clojure
(def conn (connect {:uri             "unix:///var/run/docker.sock"
                      :connect-timeout 0
                      :read-timeout    0
                      :write-timeout   0
                      :call-timeout    0}))
```
Zero signifies no timeout, following the conventions of OkHttp.

**Comment by olymk2** [comment]
To me the third option sounds like a good option, I think it needs to be configurable in some way so that you can break out of your flow easily if needed when things go wrong, but if setting no timeout matches docker it make sense that is the default, seems that's what people would expect when familiar with docker.

I will have a play with your suggestion above and see if I can get some where, my other option was to create some periodic polling of the container to check the status, but using the built in timeout is perhaps a better approach.

Thanks for your input :)

**Comment by lispyclouds** [comment]
Thanks, I am _almost_ through with the first commit implementing the third option. Stay tuned, will ask for some feedback 😄

**Comment by olymk2** [comment]
ha, great I was just starting to look myself going to go look a OkHttp not a library i am familiar with.

**Comment by lispyclouds** [comment]
There you go https://github.com/lispyclouds/clj-docker-client/commit/6a96e0102400f849bf6fa5df092821cc28d180a4
Feel free to review this! 😄

**Comment by lispyclouds** [comment]
If this looks okay, will add some docs and cut a release addressing https://github.com/lispyclouds/clj-docker-client/issues/17 too.

**Comment by olymk2** [comment]
Looks good to me, I am going to test in my project see if it works just looking how i can pull from the sha in deps.edn currently erroring with this, but most likely my bad as I have not had to use a git repo yet :)

`Error building classpath. Manifest type not detected when finding deps for lispyclouds/clj-docker-client in coordinate {:git/url "https://github.com/lispyclouds/clj-docker-client.git", :sha "6a96e0102400f849bf6fa5df092821cc28d180a4"}`

still learning some of this clojure stuff :)

**Comment by lispyclouds** [comment]
I guess its easier to clone this and running `lein install`. Saves me a lot of headache 😃

**Comment by lispyclouds** [comment]
I think using git repos from deps.edn would work if my project is deps.edn based too.

**Comment by olymk2** [comment]
ah perhaps that's the issue its expecting a deps file in your repo, will look at how to do this with lein, I am using lein but with the deps plugin as I am more familiar with clojurescript so like the consistency :)

**Comment by lispyclouds** [comment]
Yes, just clone it somewhere else and run lein install. It will override the existing 0.4.0 install with the newly compiled stuff. Your project should work as it is.

**Comment by olymk2** [comment]
okay looks pretty good, no longer getting the timeout how ever I have noticed my log stream seems to have stopped outputting, not sure if this is related but I am not aware of changes my end.

will do a bit more digging.

**Comment by lispyclouds** [comment]
Probably due to `invoke` having a change. It now takes `:as :stream` instead of `:as-stream? true`. This is to support the #17 issue. Sorry for not mentioning.

**Comment by lispyclouds** [comment]
```clojure
(def log-stream (docker/invoke containers {:op     :ContainerLogs
                                           :params {:id     "conny"
                                                    :follow true
                                                    :stdout true}
                                           :as     :stream}))
```

**Comment by olymk2** [comment]
That fixes it I have one more issue, this one could be me how ever. currently I am starting a series of containers they are on the whole working the one that failed with a timeout is now failing for another reason.

```
"Container wait 12521ef679b8ffd8f89181393cb9783938a97265d04378c8651f8ad8bb509a8b"
** ERROR: **
JVM Exception: #error {
 :cause Transport endpoint is already connected
 :via
 [{:type java.io.IOException
   :message Transport endpoint is already connected
   :at [jnr.unixsocket.UnixSocketChannel doConnect UnixSocketChannel.java 127]}]
 :trace
 [[jnr.unixsocket.UnixSocketChannel doConnect UnixSocketChannel.java 127]
  [jnr.unixsocket.UnixSocketChannel connect UnixSocketChannel.java 136]
  [jnr.unixsocket.UnixSocket connect UnixSocket.java 91]
  [clj_docker_client.socket.TunnelingUnixSocket connectSuper nil -1]
  [clj_docker_client.socket.TunnelingUnixSocket$_connect invokeStatic TunnelingUnixSocket.clj 36]
  [clj_docker_client.socket.TunnelingUnixSocket$_connect invoke TunnelingUnixSocket.clj 32]
  [clj_docker_client.socket.TunnelingUnixSocket connect nil -1]
  [okhttp3.internal.platform.Platform connectSocket Platform.kt 117]
  [okhttp3.internal.connection.RealConnection connectSocket RealConnection.kt 266]
  [okhttp3.internal.connection.RealConnection connect RealConnection.kt 180]
  [okhttp3.internal.connection.ExchangeFinder findConnection ExchangeFinder.kt 238]
  [okhttp3.internal.connection.ExchangeFinder findHealthyConnection ExchangeFinder.kt 111]
  [okhttp3.internal.connection.ExchangeFinder find ExchangeFinder.kt 79]
  [okhttp3.internal.connection.Transmitter newExchange$okhttp Transmitter.kt 163]
  [okhttp3.internal.connection.ConnectInterceptor intercept ConnectInterceptor.kt 35]
  [okhttp3.internal.http.RealInterceptorChain proceed RealInterceptorChain.kt 112]
  [okhttp3.internal.http.RealInterceptorChain proceed RealInterceptorChain.kt 87]
  [okhttp3.internal.cache.CacheInterceptor intercept CacheInterceptor.kt 82]
  [okhttp3.internal.http.RealInterceptorChain proceed RealInterceptorChain.kt 112]
  [okhttp3.internal.http.RealInterceptorChain proceed RealInterceptorChain.kt 87]
  [okhttp3.internal.http.BridgeInterceptor intercept BridgeInterceptor.kt 84]
  [okhttp3.internal.http.RealInterceptorChain proceed RealInterceptorChain.kt 112]
  [okhttp3.internal.http.RetryAndFollowUpInterceptor intercept RetryAndFollowUpInterceptor.kt 71]
  [okhttp3.internal.http.RealInterceptorChain proceed RealInterceptorChain.kt 112]
  [okhttp3.internal.http.RealInterceptorChain proceed RealInterceptorChain.kt 87]
  [okhttp3.RealCall getResponseWithInterceptorChain RealCall.kt 194]
  [okhttp3.RealCall execute RealCall.kt 67]
  [clj_docker_client.requests$fetch invokeStatic requests.clj 130]
  [clj_docker_client.requests$fetch invoke requests.clj 120]
  [clj_docker_client.core$invoke invokeStatic core.clj 133]
  [clj_docker_client.core$invoke invoke core.clj 108]
  [piper.utils.containers$wait_container invokeStatic containers.clj 78]
  [piper.utils.containers$wait_container invoke containers.clj 74]
  [piper.pipeline.core$create_then_run_container invokeStatic core.clj 55]
  [piper.pipeline.core$create_then_run_container invoke core.clj 51]
  [piper.pipeline.core$run_steps$fn__30271 invoke core.clj 72]
  [clojure.core$map_indexed$mapi__8533$fn__8534 invoke core.clj 7308]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 531]
  [clojure.core$seq__5387 invokeStatic core.clj 137]
  [clojure.core$dorun invokeStatic core.clj 3133]
  [clojure.core$doall invokeStatic core.clj 3148]
  [clojure.core$doall invoke core.clj 3148]
  [piper.pipeline.core$run_steps invokeStatic core.clj 63]
  [piper.pipeline.core$run_steps invoke core.clj 62]
  [piper.pipeline.core$run_pipeline invokeStatic core.clj 98]
  [piper.pipeline.core$run_pipeline invoke core.clj 90]
  [cli_matic.core$invoke_subcmd invokeStatic core.cljc 518]
  [cli_matic.core$invoke_subcmd invoke core.cljc 497]
  [cli_matic.core$run_cmd_STAR_ invokeStatic core.cljc 562]
  [cli_matic.core$run_cmd_STAR_ invoke core.cljc 536]
  [cli_matic.core$run_cmd invokeStatic core.cljc 574]
  [cli_matic.core$run_cmd invoke core.cljc 564]
  [piper.core$_main invokeStatic core.clj 36]
  [piper.core$_main doInvoke core.clj 34]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.core$apply invokeStatic core.clj 665]
  [clojure.main$main_opt invokeStatic main.clj 491]
  [clojure.main$main_opt invoke main.clj 487]
  [clojure.main$main invokeStatic main.clj 598]
  [clojure.main$main doInvoke main.clj 561]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.main main main.java 37]]}
```

I have not spent to much time on this, but posting it here in case you have ideas but i will try a few things my end and see if i can figure out anything else but on the whole its working well.

**Comment by lispyclouds** [comment]
Was this happening before or after this upgrade?

**Comment by olymk2** [comment]
after, before I hit the timeout issue I report I have upgraded with lein install and modified the stream as above and i can see containers starting and logging but when it hits a a specific step I get the issue above, as I have never got past that container starting I cant confirm if its my issue or related to the changes.

**Comment by lispyclouds** [comment]
I have a hunch that this is reagarding the re-use of the same UNIX socket for multiple connection which OkHttp is attempting to do and AFAIK we cannot re-use sockets. Need to implement some multiplexing I/O magic for this. A possible work around could be creating new connections for each. Could you try that? Also could you open another issue with a small repro? I think this is a separate issue.

**Comment by lispyclouds** [comment]
If this looks okay, I can cut the 0.5.0 release?

**Comment by olymk2** [comment]
well from my end I am getting further so seems good, probably not going to do much more tonight as I am getting tired but I will dig a bit more and raise an issue with what I find or report back here if it all looks good :)

**Comment by lispyclouds** [comment]
Will wait it out for your report, maybe can bundle it in this release. Thanks!

**Comment by olymk2** [comment]
opened a new issue, leave it with you the issue is likely not new so cut a release if you like.

Thanks again for the awesome support :)

**Comment by lispyclouds** [comment]
Thanks for sticking around with the feedback. Will give it some thought and probably plan a minor release.

**Comment by lispyclouds** [comment]
Closed by https://github.com/lispyclouds/clj-docker-client/releases/tag/0.5.0
