### ISSUE TITLE
Issue when connection is already in use.

### ISSUE THREAD

**Issue by olymk2** [lispyclouds/clj-docker-client#20]
Related to #19 I think your hunch was correct, basically I am starting a container attaching to the logs and then waiting on the container so I can follow the logs until completion.

because logs is watching the stream on conn and wait is using conn this is causing issues, creating conn2 and used that for logs and conn1 for all other steps and that seems to be working for now.

for my purposes this is fine, I guess might be worth a note some where unless you implement the multiplexing solution you talked about.

**Comment by lispyclouds** [comment]
Closed #25
